DEBUG_ETHERNET_PACKET = False
DEBUG_IP_PACKET = False
DEBUG_UDP_PACKET = False

DEBUG_ALL_PACKETS = False
DEBUG_ALL_PACKETS_TO_MY_MAC = False
DEBUG_ALL_PACKETS_TO_MY_IP = False
DEBUG_ALL_PACKETS_TO_MY_PORT = False
DEBUG_ALL_PACKETS_RECEIVE_MESSAGE = False

DEBUG_LISTEN = True